class wpscanTasks < Thor
  include Rails.application.config.dradis.thor_helper_module

  namespace "dradis:plugins:wpscan"

  desc      "upload FILE", "upload wpscan results in JSON format"
  long_desc "This plugin expect a JSON file generated by wpscan using: -f "\
            "jason -o results.json"
  def upload(file_path)
    require 'config/environment'

    unless File.exists?(file_path)
      $stderr.puts "** the file [#{file_path}] does not exist"
      exit(-1)
    end

    detect_and_set_project_scope

    importer = Dradis::Plugins::wpscan::Importer.new(task_options)
    importer.import(file: file_path)
  end

end
